Repository ProjetaoMUS/bike-parking-backend, pull requests merged in 2023-09, with the labels that each got.

#2 Added documentation to the readme in order to assist the dev team
  README.md
Labels: documentation

#4 Authentication
  requirements.txt
  src/bike_parking/settings.py
  src/bike_parking/urls.py
  src/user/models.py
Labels: enhancement

#9 HOTFIX: Added media_url to dev settings
  src/bike_parking/settings.py
Labels: bug

#10 Added rating field to PartnerLocation model
  src/partner_location/migrations/0002_partnerlocation_rating.py
  src/partner_location/models.py
Labels: enhancement
